version: '3.8'

services:
  api_gateway:
    build: .
    container_name: api_gateway
    ports:
      - "9000:9000"
    networks:
      - network_local_server

networks:
  network_local_server:
    external: true