version: '3.8'
services:
  sqlite:
    container_name: serve-sqlite
    image: nouchka/sqlite3:latest
    restart: always
    volumes:
      - ./data:/data
    networks:
      - network_local_server
    labels:
      - com.corhuila.group=databases
networks:
  network_local_server:
    driver: bridge
    name: network_local_server