version: '3.8'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:9000"
      - "--providers.file.filename=/middlewares.yml"
    ports:
      - "9000:9000"  # Expose HTTP on port 9000
      - "8080:8080"  # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./middlewares.yml:/middlewares.yml"
    networks:
      - network_local_server

  backend-security:
    image: devops-backend-security
    container_name: backend-security
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-security.rule=Host(`localhost`) && PathPrefix(`/auth`)"
      - "traefik.http.services.backend-security.loadbalancer.server.port=9000"
    networks:
      - network_local_server

  backend-ubication:
    image: devops-backend-ubication
    container_name: backend-ubication
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-ubication.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend-ubication.loadbalancer.server.port=9000"
      - "traefik.http.routers.backend-ubication.middlewares=jwt-auth@file"
    networks:
      - network_local_server

networks:
  network_local_server:
    external: true