version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: serve-cassandra
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_LISTEN_ADDRESS: auto  # Configura Cassandra para que elija automáticamente la IP correcta
      CASSANDRA_BROADCAST_ADDRESS: auto  # Configura automáticamente la dirección de broadcast
      CASSANDRA_SEEDS: serve-cassandra  # Usa el nombre del contenedor como semilla en lugar de la IP
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USERNAME: admin
      CASSANDRA_PASSWORD: abcd1234
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - network_local_server
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u admin -p abcd1234 -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.corhuila.group=databases
volumes:
  cassandra_data:
    driver: local
networks:
  network_local_server:
    driver: bridge
    name: network_local_server