version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: serve-cassandra
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_DC: DC1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_LISTEN_ADDRESS: 172.18.0.6  # Usa la IP del contenedor
      CASSANDRA_BROADCAST_ADDRESS: 172.18.0.6  # Usa la misma IP del contenedor
      CASSANDRA_SEEDS: 172.18.0.6  # También usa esta IP como semilla
      CASSANDRA_AUTHENTICATOR: PasswordAuthenticator
      CASSANDRA_USERNAME: admin
      CASSANDRA_PASSWORD: abcd1234
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - network_local_server
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -u admin -p abcd1234 -e 'describe cluster'"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - com.corhuila.group=databases

volumes:
  cassandra_data:
    driver: local

networks:
  network_local_server:
    external: true