version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:9000"
    depends_on:
      - auth-server
      - backend_security
      - backend_ubication

  auth-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend_security:
    image: tu-imagen-de-backend-seguridad
    ports:
      - "9001:9001"

  backend_ubication:
    image: tu-imagen-de-backend-ubicacion
    ports:
      - "9002:9002"