version: '3.8'

services:
  kong:
    build: .
    container_name: kong
    ports:
      - "9000:8000"  # Puerto para las API proxy
      - "8443:8443"  # Puerto para las API proxy (HTTPS)
      - "8001:8001"  # Puerto para la API administrativa
      - "8002:8002"  # Puerto para Kong Manager (HTTP)
      - "8445:8445"  # Puerto para Kong Manager (HTTPS)
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8445 ssl"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002, 0.0.0.0:8445 ssl"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_LOG_LEVEL: debug
    networks:
      - network_local_server

  backend_security:
    image: devops-backend-security:latest
    container_name: backend-security
    ports:
      - "9001:9000"
    networks:
      - network_local_server

  backend_ubication:
    image: devops-backend-ubication:latest
    container_name: backend-ubication
    ports:
      - "9002:9000"
    networks:
      - network_local_server

networks:
  network_local_server:
    external: true
